apiVersion: v1
kind: Service
metadata:
  name: webtop
  labels:
    app: webtop
spec:
  type: ClusterIP
  selector:
    app: webtop
  ports:
    - name: https
      port: 3002
      targetPort: 3002
    - name: http
      port: 3003
      targetPort: 3003
