apiVersion: ENC[AES256_GCM,data:Tes=,iv:m0Nq+mcR20q2oBT8i53QlTUs+YOzU89VxJFkRXgUmus=,tag:zaEp08ioePDz3L7YIzOA7Q==,type:str]
kind: ENC[AES256_GCM,data:573DSqpx,iv:T22KPzsABlSg/WRmgX0+14C+nC9+zyKOhVQCBthAaaM=,tag:cbHxH6WM2wrNPzj9QwzX4Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:d4qeGkzU2fIl8P0A6HcThJVXnKIqLeNI,iv:PLLp+7db61IySaxeYlheaIoQmMYThVtcqSRgUkdYP0E=,tag:snHEQLPbt5soH3OJMvk2DQ==,type:str]
    namespace: ENC[AES256_GCM,data:WzU7plQzl2Yq,iv:HmLbN5zPxK/Mh2Soq6oTeycHINPBSGkCj+M7gBSWems=,tag:+ozoS1xGkZhDZeNTYL3TLQ==,type:str]
type: ENC[AES256_GCM,data:oWnjb5aX,iv:4gBcspApgz6kcv/RlvyQai0TBIfg5VN0iQTLYX9QeRQ=,tag:WmVI+ZUOv0YlQZGQD3wtOA==,type:str]
stringData:
    clientId: ENC[AES256_GCM,data:m2nu0w0D1voeSyHdEOR+77s=,iv:YDREpQY7ftdpLfOX1mn8NOFLXLDYkSLdjxlX60GPjW0=,tag:uYPiMH1rfmB4WKIyxL3fQw==,type:str]
    clientSecret: ENC[AES256_GCM,data:7LRY9hM9+RaLU0FBbOTmsoWezKJQG3qRWCexpzaJUsQZu7FXue+7cK5oA9u6tQbhnurtgDDbHUm8s/ShtPhp,iv:VkBkBy5QhQBNZFWVsOk5kwKjSADde3pO6cdIRVYyLLQ=,tag:g9UZPYWAzkScdyaYA8s/0g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZL2R4Yk8vVzB2WHZQa3VB
            NGp0ek5ITVhENjN2SERyVFNsV1JPMWdlejBvClRFcGlJK2FrUnZOZkcrL2JzWEJJ
            OU9zR3FCZ090UnBPMS9RVmsxelM5Z0kKLS0tIFl4NUwzN3E4N3ZGUGVRbGNqb3c4
            UER0ZmZNYU1nYms5dzF3UmhhQTA1c00KOR7a89NG1s4QFDzb2hdbGnlvLJ+yCrQX
            UVVisfxWNE1txUWWrqp1+mba9Qhd/coMyPYwrNQ4TwbAIGDjYilBXQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m47tw0h4rvjlrqrr8mca4qkftfqf0pwen203a622z69kfjk6wvgqc9emky
    lastmodified: "2026-08-27T11:57:34Z"
    mac: ENC[AES256_GCM,data:pJ0T1voZxKvJfJEbqaz5n3bltC//OsPuWNMcqSvN77SzFXNMupyT/CXycW+1waGcGb5icsA0cpf53+zi8+NIP1g9o7JR4qh8JCDc+YxhzXlm4S5HiAEtB8QixBLYN0IEMrxFAwAhdN+J/cWkZwEnbKslOdExJA1y8sVq7rHNFnQ=,iv:aiWQLbk2YQo9xVAAl1SAiyvzRvN+/WQ/0uxRqHT86E4=,tag:AdUuWtRveWgzxP4ZgoQYgA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
