apiVersion: v1
kind: Secret
metadata:
    name: tailscale-operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    clientId: ENC[AES256_GCM,data:NTLkCgcxl9PUs1CHnv1VoMI=,iv:rRy8fLn1FvAU8vb/7v6VJiXlMoOMfghoPTJQ/6aMYaY=,tag:ZH1BwE7QnDCsM8c8xoLtuA==,type:str]
    clientSecret: ENC[AES256_GCM,data:5N6/A6A1L8WY6O4NasPCMr3Qg4xj60TYqNgSy+MDEyUDKF3SRqxX2A24N52FgiTg1OL60DB0y/2MXDgZeGmz,iv:cA6E5a8eYPzD76sk0Y11rm9PQrXskZ2ex3pSqUtjfj0=,tag:N4kjShiT8weFmE9/w+43+A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZHdhS3l4eGE0L1FIc0VE
            TXc1T21XY0JOTHBhUVNsRGxsdytZd1o0THlnCnVwOC9sV0lCeCtJUGFKNkh4bmx6
            RUp4MjlHZ2tLSXdESFlwSGlzUWdKZ1kKLS0tIEYxYk44S29zWWRGeDBJTVpuZGRz
            RW5PYi9lSXZqd2pvTlEzdUF5dW5GRlUK4hcUcxbBObRQgSF5xIdiBObSg5lPDOen
            O7cAnoYk7HMIq0CLzlpA6T1cNWyNFb6xcFvQFdM47IMI4jyoGhDzYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m47tw0h4rvjlrqrr8mca4qkftfqf0pwen203a622z69kfjk6wvgqc9emky
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-27T15:45:20Z"
    mac: ENC[AES256_GCM,data:7zG0NcOM1katSnLpwyafnqdjC89nwiDbcswRJC5XmRiCz6nD6LgknD1ovTFkgKa8SqwiaKYgoqAweYSx0EmD+UmiV566AS3Wbp/QTC0mqc+9eFyJOBvUTIt+PSfV+tAf5ElHJz1Fxj0jAWmjiozU4dEx5X/QfeVehCv+MzquPTo=,iv:DaooHylgnd4ss1fwS58ktqbYDWbX1IPWmHv08kf1djw=,tag:Wqy7UoZP9zmH+iXrBg4+6A==,type:str]
    version: 3.13.2
