apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-pvc-data
  namespace: obsidian-sync
spec:
  storageClassName: nfs-hdd
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
