apiVersion: v1
kind: Secret
metadata:
    name: couchdb-auth
    namespace: livesync
type: Opaque
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:cCgm,iv:eIhtcvapqbAFNlAVjoFY/DWcSVgKq/f9Er0NANj09dE=,tag:WViJ/0x3nZEJIbmc/FaXrQ==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:ZZ1NjLo0cpst3w==,iv:hy5PZmSzUMdldBcMVuqu8iBa+aVCnmZVhNTNn53RAsM=,tag:CRNGuX/Zhwdg44uVcM3CDA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2T2VabFlEVVZERDF1dnVQ
            eEVyRnZuYy9HSVUrQVlmUGhlWkJGN0RvNkZNCkhxUS9jQktlRDB0THA5MFhFeGI0
            bGpIOVBWdmV5bDF3LytzcEdJR1JwNFUKLS0tIHdEWG9aNE5ybjhUOFYxRVVMWHVZ
            VDJaZ1FCZDBabnc3QklueWZBMmlhdmMKn+Bw2AKnH8I3soLN4troS+1/fddm8nAP
            ADnh2szMzDycNNfiPKiPNUbeR0WAnm2Zmk7NK6NBGaelFTbb6hGXmw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m47tw0h4rvjlrqrr8mca4qkftfqf0pwen203a622z69kfjk6wvgqc9emky
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-27T15:43:02Z"
    mac: ENC[AES256_GCM,data:XjMhYd5QOmt1CXHHZu4rzAZuC8Ps2PPe6CPDH+Us2dHEc0fwJ6cR0RBlODlAjvAqd5huaru4wyATzamn4Yy8OXRQ4OwTxvehEi7XFrx6CdNq3jJh1VHCoOtrvo90Ccr6O/danWr9L+eld1gmE2CLXeWmVXRV6pezBuqZVAdSdvk=,iv:FB1p5IWLkETsNEO1qjXxspIxhED/XxbNA0R7MxUKMNE=,tag:U0vaMTYplSmoY8LBrulHKQ==,type:str]
    version: 3.13.2
