apiVersion: ENC[AES256_GCM,data:O2k=,iv:odZk4f04n97YYb/U/zChgUlDSvjdH/ry/QfqxZUghDY=,tag:YqUa+u4GgchyVJHZw1sR7w==,type:str]
kind: ENC[AES256_GCM,data:p0Cu+xH5,iv:7rmT9/9DdeKIF6pCUcB6q4d+jVSUgp9qaKvOQo0kSAM=,tag:MueAUapa1VyUjVtR+8Karw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:H9JLxOzU60RS1wde,iv:GZIwNWMZtfvRxHrQ2dK1YT/x76Y8Gdl1/vFV76TKdgY=,tag:cUX6Xll6jj/MtuA/T5uHHA==,type:str]
    namespace: ENC[AES256_GCM,data:7bEiy/XFTFs=,iv:ABse6zk4PIdDvRgmU2TPK6g4flJ/ACsvR1zpmEtq8qk=,tag:TDKddpFjaaVQ1T4qRG7Ndg==,type:str]
type: ENC[AES256_GCM,data:KMTHjy4u,iv:ae5cpLUpD5nBVMg2cm7Ek2n+woEa8yYoE0yMUFpv4C8=,tag:otBX7EqGH9CiaOdj8e1Trw==,type:str]
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:I8YP,iv:/k443eCA6Jkjek6gUOjapsjLa66M7xsaWxIPLaCf7qc=,tag:SVsUOxrqZc0ZaqLDv9sjhQ==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:ZogePxyPvswgeA==,iv:6eTtv/vGF0PjJq5hj++/76Sp8gtTDoyLK3yRdowBdxs=,tag:aQ49UnPrfiqTS2/nVZE8MQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuYnhpaXY3bHlwcGpXdUpQ
            Q2V6MWZScVNZOU9PNnNWS1ZLWHQ0OW0yYm5BClhISEI4TFpJZm81V1VjR1RYdnRR
            V2hFWlNaamowZWtIQzNTWTFpdHJnNWMKLS0tIERqczJJV2RkRmR1S2hlMFNHSWhB
            UHR5Qld4VlhjSkw5cjVNbmN3NzVrWnMK5aQTqTM8R3OoK4OZJ976jmWiyaNXljLX
            Ymtonvbed49OJH27+6BeSzJl3rXvuZo083ZNVZxcTCEdnyl9ylZLsQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m47tw0h4rvjlrqrr8mca4qkftfqf0pwen203a622z69kfjk6wvgqc9emky
    lastmodified: "2026-08-27T14:19:49Z"
    mac: ENC[AES256_GCM,data:Bdng8xXpzKq32eWCwaHQk7sHDZ0yjiydmc3ZVB1QWKaVe6gPwmqde9qVRF/ZSffFol1Rn+ZjnlHa4nPa7spVuX5EC+i2XEFfpmon7Q3fEIXinieEJmxZssYo80LOpYO0AYIzMLWHzEFMHSK4ozeRKzb4NPiHsbGnzsbPPE7B0rM=,iv:a01S3j02WSelcBVUPpRt1x7F4xWjd1I6GBuo6AVY1b8=,tag:EqgvU0J/Ry2n+A4h4kZoaQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
