apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: livesync
resources:
  - ../../base/livesync/
  - ingress.yaml
  # Uncomment after sops-encrypting couchdb-secret.yaml
  - couchdb-secret.yaml
