apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:JZtU35Tyb1TPzlJFvHD9nIIa/718KQ24aXxNdohxlTE6IhUxjId6x+k53DlObuzYUc/7SWy3SJ3UpNRrNxgMiOkzZSO8JIL0Jb21Va+vdOy9eHpc4vcBOHPzaUAEkCQpizO3aju8zf+i2gb2zIYQsVK662jAsM7KZK0K3VyP0c1ml7PionYzrf2sjBTZrW4bAXHQL8P0nW7oU8Qn2fTSs69VyHmDFAZ+EDhIKtdT5lB93zRh60nwEWwD3NfYB5jGB8Jc5laJhEXiB9bZVIXNvMQq5r28rpAyHHYs7SIzaEYwzrl9wWRA3Wigl2M=,iv:xfKrZpF9qOiBhTT/BjHUsl4TXSTGdvUj7Bq4UpnCoYw=,tag:hGD/EgHL71iZplTZDoG2Vg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Qm54SmZKK0FjMjYzQlF0
            NUp2T1d1YUJJRzcyNkl1ZnlabFQ5VktsclU0CkJvWStzcm1iK1FLeldBMkRoWGxG
            NUNKaTM2UC9aeDVENzhhOHR3R1k4VTQKLS0tIEZPY0ErWXhXQldHaUF6U2VHTVcv
            KzlsbUdldEdrYVErNHV4UkhNRTk5Mm8KNRSTHinHp1o63WI8V3WWNs07rMj5q/zC
            d8sZRS+5VNdHMdXpCdH8lua1ZKwFxHQ0TtdW9jogK/ACt1lB3QpFxw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m47tw0h4rvjlrqrr8mca4qkftfqf0pwen203a622z69kfjk6wvgqc9emky
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T14:09:19Z"
    mac: ENC[AES256_GCM,data:weX45FpvbSID15eyJz+OUrPaGPL7W7vN2KTPbISGglSuE6SClb2myWNsnvm07dQV4mSImdssrRkLadRuDA3ss4NXQmEmsXpBOaeyG+r1S+apieiW++hkFfDXYHx09A2vtm+5M0M3FSad1mn1JjMB0UHjrKg35BII3J0S4sSjScQ=,iv:C2i66EjDkQWozYjy+615kQJlPrjcOIPUA+V8XlYjlmo=,tag:HZ6iHq9JGkWbkgEBdslZ9g==,type:str]
    version: 3.13.2
