apiVersion: v1
kind: Secret
metadata:
    name: couchdb-secret
    namespace: obsidian-sync
type: Opaque
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:NfYi7TiqWZ0q,iv:cu4FO4TFoV6hegMofQVzMIg4jBhJ7UptaGZraMrKoqM=,tag:mLfuDUennKVz8TK8z1pBWA==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:KPMd9PhAe/DxrAd6,iv:4ElckFUqTPjd6LenrjnyLQjXl2+HU1QnxNT7TNb/tsA=,tag:xNz0NwctRuSuOozSq2OCMQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUjdYdkwzSGQ1NUw1UTFK
            bEsvUUdBRWViL0FmYmkwc2ZkMXdxZ3ZLR3o0CnZYWWtUQkJUejcxRDdEQjVjNlY1
            SDVUN3M1d0FKNkk1ckp3dFp1R29iNFUKLS0tIFl3T29SRUxZK0NDOXpsUGZueU1E
            V1NRRXY2QW9mWEE0SlN2RGk5cDdzQ2cKg2Rpz0oU/Q67oLlZcAZjFDhKJi40fMHh
            BIbd7zJP3hHkwd6pDOPfHUqC9LfGtIKbEKx0ZY7okALEEc5VQvWY4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m47tw0h4rvjlrqrr8mca4qkftfqf0pwen203a622z69kfjk6wvgqc9emky
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-20T15:29:29Z"
    mac: ENC[AES256_GCM,data:jaXKQICTJsJOtq9i+defv2H2mWHZYdE3aVzwNjkbftZNITcMNejZUMtRR6gKpORy1IeHqvyu5vvsMaVqiI2bUdHPjYkoko9NYj8Eam0EF9HsAzRiQOJcR0BpyZndk9KeapcJmykvVzO36zKloV8S0i4+mkhxK+3zhSz7D38e8C8=,iv:IoH/6sbr/3Uvk0mWjdiiFaoJaq4WChfqG8MbPbjiHxc=,tag:022hyT9j0OHgQmfWJvXZ9g==,type:str]
    version: 3.13.2
---
apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:x8LSGdoUVZpKMZPwAjc8sT4igEYBQzOvVYP6UYxzzHq1mK9UGLfyUziBxf72+Aj3LQdinjwsPRcPkcuxFfg2+l2na5CZfw/PbFWVYvE2W9xJ7SYmPMigvxGmUab4LaLI4J5w1yL8x0gIFei5ChkDHPv3SkW/RxW2g2xKFN/0ZZYkLd6rt4N52uDwT+Vvc2jDJVdK8JVk+Oqe6c6AYMmvGmzz7SEVh77g5PQir/5QESXToj5S7d5dPWYyaqb6oA9C/BZi4EgLHwK0LGtBAIlmXPI5cPtIMHMutnoWaN5gvJrS74n8+QRNeSYLdeE=,iv:z34p539ak51wKTTR5/LEcaZP0oGE9G9lYFnVtUtrNp8=,tag:BEROvdDrjwBEHmk+W/A7FA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials-obsidian
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUjdYdkwzSGQ1NUw1UTFK
            bEsvUUdBRWViL0FmYmkwc2ZkMXdxZ3ZLR3o0CnZYWWtUQkJUejcxRDdEQjVjNlY1
            SDVUN3M1d0FKNkk1ckp3dFp1R29iNFUKLS0tIFl3T29SRUxZK0NDOXpsUGZueU1E
            V1NRRXY2QW9mWEE0SlN2RGk5cDdzQ2cKg2Rpz0oU/Q67oLlZcAZjFDhKJi40fMHh
            BIbd7zJP3hHkwd6pDOPfHUqC9LfGtIKbEKx0ZY7okALEEc5VQvWY4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m47tw0h4rvjlrqrr8mca4qkftfqf0pwen203a622z69kfjk6wvgqc9emky
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-20T15:29:29Z"
    mac: ENC[AES256_GCM,data:jaXKQICTJsJOtq9i+defv2H2mWHZYdE3aVzwNjkbftZNITcMNejZUMtRR6gKpORy1IeHqvyu5vvsMaVqiI2bUdHPjYkoko9NYj8Eam0EF9HsAzRiQOJcR0BpyZndk9KeapcJmykvVzO36zKloV8S0i4+mkhxK+3zhSz7D38e8C8=,iv:IoH/6sbr/3Uvk0mWjdiiFaoJaq4WChfqG8MbPbjiHxc=,tag:022hyT9j0OHgQmfWJvXZ9g==,type:str]
    version: 3.13.2
