apiVersion: apps/v1
kind: Deployment
metadata:
  name: audio-book-shelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audio-book-shelf
  template:
    metadata:
      labels:
        app: audio-book-shelf
    spec:
      restartPolicy: Always

#      securityContext:
#        fsGroup: 1000
#        runAsUser: 1000
#        runAsGroup: 1000

      containers:
        - name: audio-book-shelf
          image: ghcr.io/advplyr/audiobookshelf:2.17.2
          ports:
            - containerPort: 3005
              protocol: TCP

          securityContext:
            allowPrivilegeEscalation: false

          envFrom:
            - configMapRef:
               name: audio-book-shelf-configmap
#            - secretRef:
#                name: audio-book-shelf-container-env

          volumeMounts:
            - name: audio-book-shelf-config
              mountPath: /config
            - name: audio-book-shelf-metadata
              mountPath: /metadata
            - name: audio-book-shelf-podcasts
              mountPath: /podcasts
            - name: audio-book-shelf-audiobooks
              mountPath: /audiobooks
      volumes:
        - name: audio-book-shelf-config
          persistentVolumeClaim:
            claimName: audio-book-shelf-config
        - name: audio-book-shelf-metadata
          persistentVolumeClaim:
            claimName: audio-book-shelf-metadata
        - name: audio-book-shelf-podcasts
          persistentVolumeClaim:
            claimName: audio-book-shelf-podcasts
        - name: audio-book-shelf-audiobooks
          persistentVolumeClaim:
            claimName: audio-book-shelf-audiobooks
