apiVersion: v1
kind: ConfigMap
metadata:
  name: couchdb-local-ini
  namespace: livesync
data:
  livesync.ini: |
    [chttpd]
    bind_address = 0.0.0.0
    port = 5984
    require_valid_user = true
    enable_cors = true
    max_http_request_size = 4294967296

    [chttpd_auth]
    require_valid_user = true
    authentication_redirect = /_utils/session.html

    [httpd]
    enable_cors = true
    WWW-Authenticate = Basic realm="couchdb"

    [cors]
    credentials = true
    origins = app://obsidian.md,capacitor://localhost,http://localhost
    headers = accept, authorization, content-type, origin, referer
    methods = GET,PUT,POST,HEAD,DELETE
    max_age = 3600

    [couchdb]
    single_node = true
    max_document_size = 50000000
