apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  # NFS PVC retired — hostPath is in deployment.yaml ; might try to configure nfs later
  # - storage.yaml
  - job-init.yaml